language: python
sudo: required
matrix:
        include:
                - python: "3.6"
                  env: PYTHON_BINARY="python3.6"
                  addons:
                          apt:
                                  sources:
                                          - deadsnakes
                                  packages:
                                          - python3.6
                                          - python3-setuptools
                                          - python3-dev
script:
        - python3 manage,py test
                         
