dist: trusty
sudo: false

matrix:
        fast_finish: true
language: python
python:
        - 2.7
        - pypy2.7-5.8.0
        - 3.4
        - 3.5
        - nightly
        - pypy3.5-5.8.0
install: 
        # upgrate setuptools firs to work around https://github.com/pypa/setuptools/issues/1257
        - if[[ $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then travis_retry pip install -U setuptools; fi
             - if[[ $TRAVIS_PYTHON_VERSION == 2* ]]; then travis_retry pip install mock monotonic; fi
        - if[[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then travis_retry pip install mock; fi
        
        - if[[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then travis_retry pip install pycurl; fi

        - if[[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then travis_retry pip install Twisted; fi
        - if[[ $TRAVIS_PYTHON_VERSION != '2.7' || $TRAVIS_PYTHON_VERSION == '3.6' ]]; then travis_retry pip install sphinx sphinx_rtd_theme; fi
        - if[[ $TRAVIS_PYTHON_VERSION != '3.6' ]]; then travis_retry pip install flake8; fi
        - if[[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then export TORNADO_EXTENSION1; fi
        - travis_retry python setup.py install
        - travis retry pip install codecov virtualenv
        - virtualenv ./nodeps
        - ./nodeps/bin/python - VV
        - ./nodeps/bin/python setup.py install
        - curl-config --version; pip freeze
script:
        python manage.py test polls
